{{- if not .Values.config.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipery-release-bot.configName" . }}
  labels:
    {{- include "pipery-release-bot.labels" . | nindent 4 }}
data:
  {{ .Values.config.secretKey }}: |
    {{- toPrettyJson .Values.config.data | nindent 4 }}
{{- end }}
