{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pipery-release-bot.configSecretName" . }}
  labels:
    {{- include "pipery-release-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.secretKey }}: |
    {{- toPrettyJson .Values.config.data | nindent 4 }}
{{- end }}
{{- if and (not .Values.privateKey.existingSecret) .Values.privateKey.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pipery-release-bot.privateKeySecretName" . }}
  labels:
    {{- include "pipery-release-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.privateKey.secretKey }}: |
    {{- .Values.privateKey.value | nindent 4 }}
{{- end }}
{{- if and (not .Values.apiToken.existingSecret) .Values.apiToken.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pipery-release-bot.apiTokenSecretName" . }}
  labels:
    {{- include "pipery-release-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.apiToken.secretKey }}: {{ .Values.apiToken.value | quote }}
{{- end }}
