name: Pipery Go CI

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pipery-dev/pipery-golang-ci@v1.0.2
        with:
          go_version: "1.22"
          tests_path: "./..."
          image_name: ghcr.io/${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_release: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
          skip_reintegration: "true"

  argocd-release:
    needs: ci
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Publish ArgoCD Helm chart update
        uses: pipery-dev/pipery-argocd-cd@main
        with:
          publish_helm_chart_update: "true"
          argocd_repository: pipery-dev/pipery-argocd
          argocd_repository_token: ${{ secrets.PIPERY_ARGOCD_TOKEN }}
          app_name: pipery-release-bot
          app_namespace: pipery
          chart_path: charts/pipery-release-bot
          chart_target_revision: ${{ github.ref_name }}
          image_repository: ghcr.io/${{ github.repository }}
          image_tag: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
          commit_user_name: pipery-release-bot
          commit_user_email: pipery-release-bot@users.noreply.github.com
